# Generated by Django 4.2.7 on 2025-12-11 16:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='depenses.categorie')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['categorie', 'nom'],
                'unique_together': {('categorie', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('closed', 'Clôturée')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='depenses.categorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsions_created', to=settings.AUTH_USER_MODEL)),
                ('sous_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='depenses.souscategorie')),
            ],
            options={
                'verbose_name': 'Prévision',
                'verbose_name_plural': 'Prévisions',
                'ordering': ['-mois', 'categorie', 'sous_categorie'],
                'unique_together': {('mois', 'categorie', 'sous_categorie')},
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('jour', models.IntegerField(help_text='Jour du mois (1-31)')),
                ('semaine_iso', models.IntegerField(help_text='Numéro de semaine ISO (1-53)')),
                ('unites', models.DecimalField(decimal_places=2, help_text="Nombre d'unités", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_depense', models.DecimalField(decimal_places=2, help_text='Montant total dépensé (calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='depenses.categorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created', to=settings.AUTH_USER_MODEL)),
                ('sous_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='depenses.souscategorie')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_operation', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Imputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_impute', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imputations_created', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='depenses.operation')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='depenses.prevision')),
            ],
            options={
                'verbose_name': 'Imputation',
                'verbose_name_plural': 'Imputations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['date_operation'], name='depenses_op_date_op_4df4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['categorie', 'sous_categorie'], name='depenses_op_categor_7dfefe_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['semaine_iso'], name='depenses_op_semaine_58ebcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imputation',
            unique_together={('operation', 'prevision')},
        ),
    ]
