# Generated by Django 4.2.7 on 2025-12-13 14:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(help_text='Date de consommation')),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('livree', 'Livrée')], default='brouillon', max_length=20)),
                ('montant_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total avant subvention', max_digits=18)),
                ('montant_subvention', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la subvention', max_digits=18)),
                ('montant_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant net à imputer au budget (brut - subvention)', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(blank=True, help_text='Opération budgétaire liée (créée à la validation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='depenses.operation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande', '-created_at'],
                'unique_together': {('utilisateur', 'date_commande')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_menu', models.DateField(help_text='Date du menu (ex: 2026-01-18)', unique=True)),
                ('publication_at', models.DateTimeField(blank=True, help_text='Date de publication', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-date_menu'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('categorie_restau', models.CharField(choices=[('PetitDej', 'Petit-déjeuner'), ('Dejeuner', 'Déjeuner'), ('Diner', 'Dîner'), ('Snack', 'Collation')], max_length=20)),
                ('prix_standard', models.DecimalField(decimal_places=2, help_text='Prix catalogue standard (GNF)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['categorie_restau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RegleSubvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_subvention', models.CharField(choices=[('AUCUNE', 'Aucune subvention'), ('FIXE', 'Montant fixe par plat'), ('POURCENT', 'Pourcentage du montant')], default='AUCUNE', max_length=20)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe (GNF) ou pourcentage (0-100)', max_digits=18, null=True)),
                ('plafond_par_jour', models.IntegerField(blank=True, help_text='Nombre maximum de plats subventionnés par jour', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('effectif_de', models.DateField(blank=True, help_text='Date de début de validité', null=True)),
                ('effectif_a', models.DateField(blank=True, help_text='Date de fin de validité', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de Subvention',
                'verbose_name_plural': 'Règles de Subvention',
                'ordering': ['-effectif_de', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_jour', models.DecimalField(decimal_places=2, help_text='Prix du jour (peut différer du prix standard)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_max', models.IntegerField(blank=True, help_text='Stock maximum (NULL = illimité)', null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_plats', to='depenses.menu')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_plats', to='depenses.plat')),
            ],
            options={
                'verbose_name': 'Plat du Menu',
                'verbose_name_plural': 'Plats du Menu',
                'ordering': ['ordre', 'plat__nom'],
                'unique_together': {('menu', 'plat')},
            },
        ),
        migrations.CreateModel(
            name='CommandeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment de la commande', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='depenses.commande')),
                ('menu_plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_lignes', to='depenses.menuplat')),
            ],
            options={
                'verbose_name': 'Ligne de Commande',
                'verbose_name_plural': 'Lignes de Commande',
                'ordering': ['commande', 'menu_plat__ordre'],
            },
        ),
    ]
