# Generated by Django 4.2.7 on 2025-12-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_commande_menu_plat_reglesubvention_menuplat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FenetreCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_restau', models.CharField(choices=[('PetitDej', 'Petit-déjeuner'), ('Dejeuner', 'Déjeuner'), ('Diner', 'Dîner'), ('Snack', 'Collation')], max_length=20, unique=True)),
                ('heure_limite', models.TimeField(help_text='Heure limite pour commander (ex: 10:00)')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fenêtre de Commande',
                'verbose_name_plural': 'Fenêtres de Commande',
                'ordering': ['categorie_restau'],
            },
        ),
    ]
