# Generated by Django 4.2.7 on 2025-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_fenetrecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='token_public',
            field=models.CharField(blank=True, help_text='Token pour accès public', max_length=64, null=True, unique=True),
        ),
    ]
