# Generated by Django 4.2.7 on 2025-12-16 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_menu_token_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(help_text='Date de la facture (une facture par jour)', unique=True)),
                ('numero_facture', models.CharField(help_text='Numéro unique de la facture', max_length=50, unique=True)),
                ('total_commandes', models.IntegerField(default=0, help_text='Nombre total de commandes')),
                ('total_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_subvention', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_supplement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des suppléments (> 30 000 GNF)', max_digits=18)),
                ('fichier_pdf', models.FileField(blank=True, help_text='Fichier PDF de la facture', null=True, upload_to='factures/')),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
    ]
