# Generated by Django 4.2.7 on 2025-12-16 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depenses', '0005_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonctionnalite', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('operations', 'Opérations'), ('previsions', 'Prévisions'), ('imputations', 'Imputations'), ('rapports', 'Rapports'), ('categories', 'Catégories'), ('utilisateurs', 'Utilisateurs'), ('audit', 'Audit'), ('restauration_commandes', 'Commander (Restauration)'), ('restauration_menus', 'Menus (Restauration)'), ('restauration_plats', 'Plats (Restauration)'), ('tableau_bord_cantine', 'Tableau de Bord Cantine')], max_length=50)),
                ('peut_voir', models.BooleanField(default=True, help_text='Peut voir cette fonctionnalité dans le menu')),
                ('peut_creer', models.BooleanField(default=False, help_text='Peut créer des éléments')),
                ('peut_modifier', models.BooleanField(default=False, help_text='Peut modifier des éléments')),
                ('peut_supprimer', models.BooleanField(default=False, help_text='Peut supprimer des éléments')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Utilisateur',
                'verbose_name_plural': 'Permissions Utilisateurs',
                'ordering': ['utilisateur', 'fonctionnalite'],
                'unique_together': {('utilisateur', 'fonctionnalite')},
            },
        ),
    ]
