# Generated by Django 4.2.7 on 2025-12-19 14:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depenses', '0006_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='fonctionnalite',
            field=models.CharField(choices=[('dashboard', 'Tableau de bord'), ('operations', 'Opérations'), ('previsions', 'Prévisions'), ('imputations', 'Imputations'), ('rapports', 'Rapports'), ('categories', 'Catégories'), ('utilisateurs', 'Utilisateurs'), ('audit', 'Audit'), ('restauration_commandes', 'Commander (Restauration)'), ('restauration_valider_commandes', 'Valider les Commandes (Restauration)'), ('restauration_menus', 'Menus (Restauration)'), ('restauration_plats', 'Plats (Restauration)'), ('tableau_bord_cantine', 'Tableau de Bord Cantine')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExtraRestauration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_extra', models.CharField(choices=[('visiteur', 'Visiteur'), ('stagiaire', 'Stagiaire'), ('activite', 'Activité')], help_text='Type de personne externe', max_length=20)),
                ('nom_personne', models.CharField(help_text="Nom de la personne ou nom de l'activité", max_length=200)),
                ('date_operation', models.DateField(help_text="Date de l'opération")),
                ('plat_nom', models.CharField(help_text='Nom du plat commandé', max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantité de plats', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire du plat (GNF)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Montant total (calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Description supplémentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras_restauration_created', to=settings.AUTH_USER_MODEL)),
                ('operation', models.OneToOneField(blank=True, help_text='Opération budgétaire liée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_restauration', to='depenses.operation')),
            ],
            options={
                'verbose_name': 'Extra Restauration',
                'verbose_name_plural': 'Extras Restauration',
                'ordering': ['-date_operation', '-created_at'],
                'indexes': [models.Index(fields=['date_operation'], name='depenses_ex_date_op_ec163b_idx'), models.Index(fields=['type_extra'], name='depenses_ex_type_ex_2f2e69_idx')],
            },
        ),
    ]
