# Generated by Django 4.2.7 on 2025-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_alter_userpermission_fonctionnalite_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['utilisateur'], name='depenses_co_utilisa_291146_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_commande'], name='depenses_co_date_co_8f1682_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['utilisateur', 'date_commande'], name='depenses_co_utilisa_de6157_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['etat'], name='depenses_co_etat_7f1c56_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeligne',
            index=models.Index(fields=['commande'], name='depenses_co_command_2018fa_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeligne',
            index=models.Index(fields=['menu_plat'], name='depenses_co_menu_pl_7dc29b_idx'),
        ),
        migrations.AddIndex(
            model_name='prevision',
            index=models.Index(fields=['mois'], name='depenses_pr_mois_7a184a_idx'),
        ),
        migrations.AddIndex(
            model_name='prevision',
            index=models.Index(fields=['categorie'], name='depenses_pr_categor_8b9626_idx'),
        ),
        migrations.AddIndex(
            model_name='prevision',
            index=models.Index(fields=['mois', 'categorie'], name='depenses_pr_mois_1ce336_idx'),
        ),
    ]
