# Generated by Django 4.2.7 on 2026-01-12 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depenses', '0008_commande_depenses_co_utilisa_291146_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom descriptif du lot (ex: 'Lot Janvier 2026')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description ou notes sur ce lot')),
                ('nombre_tickets', models.PositiveIntegerField(help_text='Nombre de tickets dans ce lot')),
                ('date_validite', models.DateField(blank=True, help_text='Date limite de validité des tickets', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot de Tickets',
                'verbose_name_plural': 'Lots de Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='fonctionnalite',
            field=models.CharField(choices=[('dashboard', 'Tableau de bord'), ('operations', 'Opérations'), ('previsions', 'Prévisions'), ('imputations', 'Imputations'), ('rapports', 'Rapports'), ('categories', 'Catégories'), ('utilisateurs', 'Utilisateurs'), ('audit', 'Audit'), ('restauration_commandes', 'Commander (Restauration)'), ('restauration_valider_commandes', 'Valider les Commandes (Restauration)'), ('restauration_menus', 'Menus (Restauration)'), ('restauration_plats', 'Plats (Restauration)'), ('tableau_bord_cantine', 'Tableau de Bord Cantine'), ('extras_restauration', 'Extras Restauration (Visiteurs/Stagiaires)')], max_length=50),
        ),
        migrations.CreateModel(
            name='TicketRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(help_text='Code unique du ticket (ex: TKT-2026-XXXX)', max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('utilise', 'Utilisé'), ('annule', 'Annulé')], default='disponible', max_length=20)),
                ('date_utilisation', models.DateTimeField(blank=True, help_text="Date et heure d'utilisation du ticket", null=True)),
                ('utilisateur_beneficiaire', models.CharField(blank=True, help_text='Nom du travailleur bénéficiaire', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(help_text='Lot auquel appartient ce ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='depenses.lottickets')),
            ],
            options={
                'verbose_name': 'Ticket Repas',
                'verbose_name_plural': 'Tickets Repas',
                'ordering': ['-created_at', 'code_unique'],
                'indexes': [models.Index(fields=['code_unique'], name='depenses_ti_code_un_7f7876_idx'), models.Index(fields=['statut'], name='depenses_ti_statut_72283d_idx'), models.Index(fields=['lot'], name='depenses_ti_lot_id_1d431d_idx')],
            },
        ),
    ]
