# Generated by Django 4.2.7 on 2025-12-11 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('validate', 'Validation'), ('export', 'Export'), ('import', 'Import')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(default=dict, help_text='Changements effectués (anciennes/nouvelles valeurs)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
    ]
